server:
  port: 10005
spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1993Yy/cloud.git
          username: @git-username@
          password: @git-password@
          force-pull: true
          basedir: /tmp
          search-paths: deploy/dev,deploy/test
eureka:
  instance:
    hostname: locahost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 2
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: @eureka-server-url@

