name: cloud-dev

feign:
  hystrix:
    enabled: true  #让Fegin调用时启动熔断器(hystrix)
  compression:
    request:
      enabled: true #请求压缩
    response:
      enabled: true #响应压缩

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000   #默认1000  超时时间，
      circuitBreaker:
        errorThresholdPercentage: 50 #设置失败百分比的阈值。如果失败比率超过这个值，则断路器跳闸并且进入fallback逻辑默认值：50
        requestVolumeThreshold: 20 #在配置时间窗口内达到此数量的失败后，进行短路======(默认值：20个)
        sleepWindowInMilliseconds: 5000 #断路器跳闸后，在此值的时间的内，hystrix会拒绝新的请求，只有过了这个时间断路器才会打开闸门 默认值：5000


ribbon:  #会对get请求进行重试
  ReadTimeout: 5000 #ribbon请求连接的超时时间: 限制1s内必须请求到服务
  ConnectTimeout: 2000 #ribbon请求连接的超时时间: 限制2s内必须请求到服务