name: cloud-dev

feign:
  hystrix:
    enabled: true  #让Fegin调用时启动熔断器(hystrix)
  compression:
    request:
      enabled: true #请求压缩
    response:
      enabled: true #响应压缩

hystrix:
  command:
    default: #可以换成服务名，接口级别"BFeignClient#test()"
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 62000   #默认1000  超时时间，此时间应该大于ribbon.readtimeout  否则按这个时间短路超时
      circuitBreaker:
        errorThresholdPercentage: 50 #设置失败百分比的阈值。如果失败比率超过这个值，则断路器跳闸并且进入fallback逻辑默认值：50
        requestVolumeThreshold: 20 #在配置时间窗口内达到此数量的失败后，进行短路======(默认值：20个)
        sleepWindowInMilliseconds: 5000 #断路器跳闸后，在此值的时间的内，hystrix会拒绝新的请求，只有过了这个时间断路器才会打开闸门 默认值：5000


ribbon:  #会对get请求进行重试，重试间隔ReadTimeout
  ReadTimeout: 60000 #响应时间: 60s内响应
  ConnectTimeout: 2000 #ribbon请求连接的超时时间: 限制2s内必须请求到服务
  MaxAutoRetries: 1 #重试次数默认1
  MaxAutoRetriesNextServer: 1 #切换实例次数
  OkToRetryOnAllOperations: true #所有请求都重试，get post...
#只针对某个服务ribbon 设置
#cloud-b:
#  ribbon:
#    ReadTimeout: 5000
#    ConnectTimeout: 2000
